# This should go in ~/.gmailcli/config.yaml
InterestingMessageQuery: (myname OR to:me@gmail.com)

UninterestingLabelPatterns:
   - UnimportantLabel1
   - UnimportantLabel2

InterestingLabelPatterns:
   - IMPORTANT
   - MyImportantDir/.*

ApplyLabelOnTouch: xCliTouched
ApplyLabelToUninteresting: xCliUninteresting
ApplyLabelToInteresting: xCliInteresting
