# This should go in ~/.gmailcli/config.yaml
InterestingMessageQuery: (myname OR to:me@gmail.com)

AlwaysUninterestingLabelPatterns:
   - ManualUninterestingLabel

UninterestingLabelPatterns:
   - UnimportantLabel1
   - UnimportantLabel2

InterestingLabelPatterns:
   - IMPORTANT
   - MyImportantDir/.*

ApplyLabelOnTouch: xCliTouched

LabelColors:
   MyLabel: blue

Aliases:
   search-foo: search "\"Some fairly long search term\" $1"
   archive: search -q --archive --add-label MyArchiveLabel --uninteresting "in:inbox category:{updates forums} $1"
